---
title: "Template-Lab1-22nd August"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r}
dfPatient=read.csv("Data/emergency.csv")
```

```{r}
str(dfPatient)
```

```{r}
dfPatient$Condition
str(dfPatient$Condition)
```

```{r}
dfPatient$Insurance
```

```{r}
dfPatient[['Insurance']]
str(dfPatient[['Insurance']])
```

```{r}
dfPatient['Insurance']
str(dfPatient['Insurance'])
```

```{r}
dfPatient[,'Condition']
str(dfPatient[,'Condition'])
```

```{r}
dfPatient[2]
str(dfPatient[2])
```

```{r}
dfPatient[[2]]
str(dfPatient[[2]])

```

```{r}
dfPatient$Condition=='serious'
str(dfPatient$Condition=='serious')
```

```{r}
dfPatient[dfPatient$Condition=='serious',]
```

```{r}
sum(dfPatient$Condition=='serious')
```

```{r}
mean(dfPatient$Condition=='serious')
```

```{r}
mean(dfPatient$Insurance=='not insured')
```

```{r}
sum(dfPatient$Insurance=='not insured')
```

```{r}
dfPatientNew=read.csv('Data/emergency.csv',row.names=1,stringsAsFactors = TRUE)
```

```{r}
str(dfPatientNew)
```

```{r}
dfPatientNew$Condition=factor(dfPatientNew$Condition)
```

```{r}
categorical_cols=c('Condition','Insurance')
```

```{r}
dfPatientNew[,categorical_cols]=lapply(dfPatientNew[,categorical_cols],factor)
```

```{r}
str(dfPatientNew)
```

```{r}
mean(dfPatientNew$Insurance=='insured')/mean(dfPatientNew$Condition == 'serious')
```

```{r}
mean(dfPatientNew$Insurance=="Insured" && dfPatientNew$Condition=="serious")
```

```{r}
sum(dfPatientNew$Condition == 'serious')
```

```{r}

mean(dfPatient[dfPatient$Condition=='serious',]$Insurance=='insured')
```

```{r}
vec1=dfPatient$Condition=='serious'
```

```{r}
vec2=dfPatient$Insurance=='insured'
```

```{r}
```

```{r}

mean((vec1 & vec2)/mean(vec2))
```

`{mean(vec1 & vec2)}`

```         
```

```         
```

```         
```

```{r}
```
